version: '3'

services:
  gariondb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ../20240216.05.07.07.sql:/docker-entrypoint-initdb.d/a.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  garion-ticketsrus-web:
    build: ..
    depends_on:
      gariondb:
        condition: service_healthy
    ports:
      - 8086:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "db=server=gariondb;user id=postgres;database=postgres;password=password;"
    healthcheck:
      test: wget --tries=1 http://localhost/healthCheck || exit 1
      interval: 2s
      retries: 5
      start_period: 2s
      timeout: 10s