name: (Garion) Build and locally deploy .NET Core application to Web App TicketsRUsWebApp20240208111459
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_PACKAGE_PATH: TicketsRUs.WebApp/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: TicketsRUs.WebApp
  RUNNER: garion-ticket-runner
jobs:
  test:
    runs-on: "${{ env.RUNNER }}"
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: dotnet test "TicketsRUs.Tests"

  build:
    runs-on: "${{ env.RUNNER }}"
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
